### ISSUE TITLE
Fotorama strips alt attribute from images

### ISSUE THREAD

**Issue by philwastell** [artpolikarpov/fotorama#329]
Is there a way to stop Fotorama stripping alt attributes from images? Just had an SEO review of a new site we're building and this was flagged as quite a big issue. Thanks.

**Comment by grosssmutttr** [comment]
Unfortunately this is still not working :-(

Tried the cdnjs and the download version from http://fotorama.io/...

**Comment by sterjakov** [comment]
+++++++

**Comment by patrick-matte** [comment]
It seems the fix was never merged with the main branch.

**Comment by BackuPs** [comment]
The fix s presented here https://github.com/artpolikarpov/fotorama/pull/380/commits/53b6dcc32bede077ea9d51de672000a0a4adf76a is not correct.

Line 259 altText = $img.attr('alt');  should be altText = $img.attr('alt'),  

Just tested it and it works fine.

![image](https://cloud.githubusercontent.com/assets/6078370/22861853/2850469e-f123-11e6-9e4e-7e923bb507f9.png)

**Comment by ChristophAnastasiades** [comment]
For me this didn't work because `$img` doesn't hold the actual image but the anchor wrapping the image. So I needed to use `alt = $child.attr('alt'),title = $child.attr('title');`

**Comment by KoleW** [comment]
I downloaded the version you suggested, it was broken.  I modified the dev version of the js file on github and it is now recognizing the alt tags if you use the embedded init method:

<a href="/images/fullsize.png" alt="Fullsize alt tag"><a href="../images/thumb.png" alt="Thumb alt tag"></a>

Attached the fixed version here.  I like the control BTW, it is great. However until I fixed the alt tag issue it was unusable as no alt tag = bad with Google... :)  

I wish you would fix the JSON load method as well.  Did not have time at this point.  Fix that and the control is truly awesome.  

[fotorama.dev.zip](https://github.com/artpolikarpov/fotorama/files/998944/fotorama.dev.zip)

**Comment by BackuPs** [comment]
@https://github.com/ChristophAnastasiades  It depends on how you build the list of images. You should set the alt tag at the img element

**Comment by IvanShrt** [comment]
@KoleW Hi! I've downloaded your file, but alt tags still don't appear. Can you please specify what does the embedded init method means or how should I make it work? I've just added alt tag in a classical way, like this - alt="balbablblblab"

**Comment by sergeypedan** [comment]
Thanks @ChristophAnastasiades , that makes it work!

**Comment by IvanShrt** [comment]
@sergeypedan Hello! Can you please specify how exactly you make it work! Where have you added the piece of code @ChristophAnastasiades provided? Thank you very much!

**Comment by sergeypedan** [comment]
@IvanShrt Sure!

In file `fotorama.dev.js` version 4.6.4:

1. Add

```js
if ( frameData.data.hasOwnProperty('alt')   ) { img.alt   = frameData.data.alt; }
if ( frameData.data.hasOwnProperty('title') ) { img.title = frameData.data.title; }
```

after

```js
frameData.state = '';
```


2. Replace

```js
height = numberFromMeasure(imgData.height || $img.attr('height'));
```

with

```js
height = numberFromMeasure(imgData.height || $img.attr('height')),
alt    = $child.attr('alt'),
title  = $child.attr('title');

if (alt)   { $.extend(imgData, { alt: alt }); }
if (title) { $.extend(imgData, { title: title }); }
```

**Comment by IvanShrt** [comment]
@sergeypedan Thank you very much! Well, I've seen lot's of people were struggling with this issue all these years, I hope they will jump over this thread and see this solution. Very nice!

**Comment by sergeypedan** [comment]
Thanks for your kindness @IvanShrt  ;) I also hope someone finds it helpful.

**Comment by Ivan-ShRt** [comment]
I don't know guys, I used two different services to check if alt tags appear but it doesn't. So, these fixes don't help at all. That is sad for someone who is investing money into SEO meeehh... anyone found any other solutions?

**Comment by CrestApps** [comment]
@sergeypedan I tried your patch but it does not seem to work. I may be missing something. I downloaded the file you attached and used it as it in replacement of the shipped fotorama.js file.

@Ahmdrza Do you mind sharing with us your solution in public so others can benefit from it?

**Comment by CrestApps** [comment]
After digging into the code I was able to get @sergeypedan  patch to work by making the alt and title tags part of the data instead of a standard attribute. So my HTML markup looks like this
```
<img src="/photos/image_thumb.jpg" data-alt="some alternative text" data-title="some title" class="img-fluid" data-caption="some caption" data-full="/photos/image.jpg">
```

**Comment by ssylur** [comment]
> The fix as presented here [53b6dcc](https://github.com/artpolikarpov/fotorama/commit/53b6dcc32bede077ea9d51de672000a0a4adf76a) is not completely correct.
> 
> Line 259 altText = $img.attr('alt'); should be altText = $img.attr('alt'),
> 
> Just tested it and it works fine.
> 
> ![image](https://cloud.githubusercontent.com/assets/6078370/22861853/2850469e-f123-11e6-9e4e-7e923bb507f9.png)
> 
> You can download the dev 4.6.4 https://github.com/artpolikarpov/fotorama/releases/download/4.6.4/fotorama-4.6.4.dev.zip and then apply the suggested changes to the fotorama.js from that zip at line 1210 and (when applied at 1210) at line 2513

Thanks, im just fixing legacy project, and your tip saved my time. :)
